language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: false
before_install :
- chmod +x mvnw
script:
  - mvn sonar:sonar -Dsonar.organization=travex -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a0fbd8de5ac28eb4164491dcb69cd4ebca538c93
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
sonarqube:
    branches :
    - feature/*
notifications:
  email:
    recipients:
      - marianna.de.lima@master-developpement-logiciel.fr
      - lea.foissac@master-developpement-logiciel.fr
      - franck.picardat@master-developpement-logiciel.fr
      - hichem.rouis@master-developpement-logiciel.fr
    on_success: never
    on_failure: always